### ISSUE TITLE
Killaura, Fastbreak, Fastplace still work

### ISSUE THREAD

**Issue by ChainofChaos** [Rammelkast/AntiCheatReloaded#105]
AntiCheatReloaded version : 1.9.3
Server Software: Papermc and SpigotMC (1.16.1) (Tested on both software)
ProtocolLib version: Latest stable (4.5.1)
No ViaVersion
Killaura, Fastbreak, Fastplace still work and not blocked
Tested with Wurst client hack (killaura, Fastbreak, Fastplace)

**Comment by Oecher1** [comment]
> AntiCheatReloaded version : 1.9.3
> Server Software: Papermc and SpigotMC (1.16.1) (Tested on both software)
> ProtocolLib version: Latest stable (4.5.1)
> No ViaVersion
> Killaura, Fastbreak, Fastplace still work and not blocked
> Tested with Wurst client hack (killaura, Fastbreak, Fastplace)

tbh theres barely any info on this just he uses a certain client and so so modules work

**Comment by wvbigdave** [comment]
trajectories, boat flight, antislowdown, velocity, no slip, scaffold walk, fast bridge, horse jump, fast break, bow aimbot, trigger bot.

These still work with the Aristois client

**Comment by Rammelkast** [comment]
@wvbigdave boat flight check is on it's way, velocity will not bypass 0% and trajectories is client-side and can't be fixed.

**Comment by Rammelkast** [comment]
Closing this for invalid case and thread format. All issues need to be an individual report.
