### ISSUE TITLE
Cross Platform Broken

### ISSUE THREAD

**Issue by myk3sr** [Rammelkast/AntiCheatReloaded#106]
I have a papermc server, running geyser + floodgate, I basically have true cross platform I can host users from PC, users from consoles (Xbox, PS4, Nintendo), and mobile (Android and iOS) both users from bedrock client and java clients.  

Not sure the exact issue, but So far I have learned, each client has different client settings. . And there's no happy medium, I have not been able to get a successful configuration to work without some sort of false positive.

I do believe all if not most hackers are on PC, seems impossible to hack from consoles (maybe new detection scope)

I've noticed, speed, waterwalk, fasteat, fastladder, are the the biggest false positives detectors on my server with default config, any stair movement give an instant flag, ladders practically crash the client or user is eternally stuck on a climb rewind and can't move,

 I have to disable kicks first or the plugin will boot every console + mobile users, PC is somewhat able to accept values for my client, and the debug values are neverending.

**Comment by Rammelkast** [comment]
AntiCheatReloaded does not and will never support mobile, console and/or bedrock users.
