### ISSUE TITLE
unpatch cheats

### ISSUE THREAD

**Issue by CaptainTheBeam** [Rammelkast/AntiCheatReloaded#111]
How do i unpatch cheats im working on an anarchy server but want elytra fly to be unpatched

**Comment by Rammelkast** [comment]
You can disable a check by setting 'enabled' to false in checks.yml

**Comment by CaptainTheBeam** [comment]
Ok so after messing around with it a bit I have unpatched elytras but there is no speed cap which is a nessecity and when landing sometimes it kicks you from the server how do i make it not kick from the server ever no matter what cheats are bing used. I just want it to maybe rubber band if using speed cheats. I also made it so that strafe should work yet im still being kicked from the server.

**Comment by Geolykt** [comment]
Aren't those vanilla functions this Anticheat shouldn't touch?

**Comment by CaptainTheBeam** [comment]
No its working too well i need it to stop detecting and kicking some cheats
