### ISSUE TITLE
Unhandled Exception: Unhandled exception occured in onPacketSending(PacketEvent) for AntiCheatReloaded

### ISSUE THREAD

**Issue by Bingdom-creator** [Rammelkast/AntiCheatReloaded#113]
Example from server log:

16.10 23:25:10 [Disconnect] User Trveyupa has disconnected, reason: You logged in from another location
16.10 23:25:10 [Server] INFO Trveyupa left the game
16.10 23:25:10 [Server] ERROR Unhandled exception occured in onPacketSending(PacketEvent) for AntiCheatReloaded
16.10 23:25:10 [Server] INFO java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$be33aef0.getUniqueId(<generated>) ~[?:?]
16.10 23:25:10 [Server] INFO at com.rammelkast.anticheatreloaded.check.packet.MorePacketsCheck.compensate(MorePacketsCheck.java:98) ~[?:?]
16.10 23:25:10 [Server] INFO at com.rammelkast.anticheatreloaded.util.PacketListener$1.onPacketSending(PacketListener.java:55) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:347) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
16.10 23:25:10 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
16.10 23:25:10 [Server] INFO at net.minecraft.server.v1_16_R2.NetworkManager.b(NetworkManager.java:288) ~[patched_1.16.3.jar:git-Paper-199]
16.10 23:25:10 [Server] INFO at net.minecraft.server.v1_16_R2.NetworkManager.dispatchPacket(NetworkManager.java:244) ~[patched_1.16.3.jar:git-Paper-199]
16.10 23:25:10 [Server] INFO at net.minecraft.server.v1_16_R2.NetworkManager.sendPacket(NetworkManager.java:220) ~[patched_1.16.3.jar:git-Paper-199]
16.10 23:25:10 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1630) ~[patched_1.16.3.jar:git-Paper-199]
16.10 23:25:10 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.sendPacket(PlayerConnection.java:1603) ~[patched_1.16.3.jar:git-Paper-199]
16.10 23:25:10 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.internalTeleport(PlayerConnection.java:1307) ~[patched_1.16.3.jar:git-Paper-199]
16.10 23:25:10 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1246) ~[patched_1.16.3.jar:git-Paper-199]
16.10 23:25:10 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1230) ~[patched_1.16.3.jar:git-Paper-199]
16.10 23:25:10 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1220) ~[patched_1.16.3.jar:git-Paper-199]

**Comment by Rammelkast** [comment]
This issue was fixed as of 3b9b39c
