### ISSUE TITLE
Dependency Problems

### ISSUE THREAD

**Issue by ImFelixprogram** [Rammelkast/AntiCheatReloaded#114]
I can't build the project on my Workstation (Note: I did use Maven in Commandline, no IDE) because the Repository you're using is not containing some of the Spigot dependencies.
It would be great if you could fix that.
Maybe add the SpigotMC Maven repository to your pom.xml like I did to be able to build it.
In your repositories, add
```xml
<repository>
        <id>spigot-repo</id>
        <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
</repository>
```
in your dependencies, edit the dependencies for Spigot as follows
```xml
<dependency>
      	<groupId>org.spigotmc</groupId>
        <artifactId>spigot-api</artifactId>
      	<version>1.8.8-R0.3-SNAPSHOT</version>
      	<scope>provided</scope>
</dependency>
<dependency>
      	<groupId>org.spigotmc</groupId>
        <artifactId>spigot-api</artifactId>
      	<version>1.16.3-R0.1-SNAPSHOT</version>
      	<scope>provided</scope>
</dependency>
```
Also consider to add a dependency for the nonnull annotation processor as the project is not able to build otherwise
```xml
<dependency>
  <groupId>com.google.code.findbugs</groupId>
  <artifactId>jsr305</artifactId>
  <version>3.0.2</version>
</dependency>
```

**Comment by Geolykt** [comment]
My points of critique:
 - Adding Spigot as a repository will do nothing as this plugin uses NMS (and that for a good reason)
 - I'm pretty sure he uses the Jetbrain's annotations, not the Javax annotaions (at least the first one would make more sense) Even then the Javax annotations are included within the Spigot-API (which is included within Spigot) so no need to add it as a dependency
 - Consider using Code blocks to prove your point or at least attempt to format your XML as otherwise it's hard to read

**Comment by ImFelixprogram** [comment]
> My points of critique:
> 
> * Adding Spigot as a repository will do nothing as this plugin uses NMS (and that for a good reason)
I did suggest that change because Spigot is already added as dependency but is not included in the repository the author uses so the build fails.
> * Even then the Javax annotations are included within the Spigot-API (which is included within Spigot) so no need to add it as a dependency
Well, build fails without adding it.
> * Consider using Code blocks to prove your point or at least attempt to format your XML as otherwise it's hard to read
Could you explain how to use them as I use Github not that often and it removed the formatting in the code?

**Comment by Geolykt** [comment]
The build fails as it cannot find Spigot (not to be confused with Spigot-API), the Spigot dependency must be obtained via the build tools partially thanks to the Bukkit Drama of 2016 as well as the fact that you may not distribute minecraft.

The formatting would look like
```xml
<repository> 
  <id>spigot-repo</id>
  <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
</repository>
```
\`\`\`xml
(content)
\`\`\`

**Comment by ImFelixprogram** [comment]
@Geolykt 
> The build fails as it cannot find Spigot (not to be confused with Spigot-API), the Spigot dependency must be obtained via the build tools partially thanks to the Bukkit Drama of 2016 as well as the fact that you may not distribute minecraft.

I'm a bit confused trying to get the meaning of that sentence - but anyways, performing the changes stated in my first post solves the build problems that I get when trying to build using Maven, that's why I added that issue to suggest @Rammelkast that he adds it in his [pom.xml](https://github.com/Rammelkast/AntiCheatReloaded/blob/master/pom.xml)

> The formatting would look like [...]

Thanks, I edited the post.

**Comment by Geolykt** [comment]
It's odd that it resolves the compilation problems as it really shouldn't resolve the compilation issues as we are dealing with NMS (net.minecraft.server, I.e. not the specification, but the implementation) which is someting completely different to normal Spiot-API/Bukkit-API. To get the NMS you need to run [buildtools ](https://www.spigotmc.org/wiki/buildtools/) with the compile-craftbukkit goal first.

**Comment by Rammelkast** [comment]
As mentioned by @Geolykt, Spigot will not resolve unless you build it yourself on your system using BuildTools. It should then be added to your local repository, fixing build issues. I wish it could be easier, but sadly this is how Spigot works now.
