### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by LokiTheGod123** [Rammelkast/AntiCheatReloaded#115]
Hi! What are the permissions and can you add xray to the plugin?

**Comment by LokiTheGod123** [comment]
Also, what placeholders does this plugin have? I would like to create a hologram with hd displays saying how many players were banned by the anticheat.

**Comment by Rammelkast** [comment]
The plugin does not have placeholders. As for anti-xray, this will never be added. It is an incredible performance hog and is a native feature in PaperSpigot servers. For permissions, see https://github.com/Rammelkast/AntiCheatReloaded/blob/master/src/main/resources/plugin.yml#L14
