### ISSUE TITLE
Fly

### ISSUE THREAD

**Issue by LokiTheGod123** [Rammelkast/AntiCheatReloaded#117]
Hi. Sorry for opening another issue. When my players jump from high locations they are banned for flying and speed. I have dropper on my server and it’s very annoying when it bans them for flying when they are playing a game. Any fix? Also, is it possible to disable worlds?

**Comment by Rammelkast** [comment]
Turn on debug-mode in config.yml to get advanced messages about what's wrong and where to change it. You can also disable worlds at the bottom of config.yml. Github issues is however for problems with the plugin. For normal support please PM me on Spigot or use the discord.
