### ISSUE TITLE
Unhandled exception: SWAP_ITEM_WITH_OFFHAND

### ISSUE THREAD

**Issue by xenoflot** [Rammelkast/AntiCheatReloaded#120]
Here's the log excerpt:  https://gist.github.com/xenoflot/b1a74c3dc7dcab1c7e51ecc0b472514d

I know the player is running Wurst. He won't be deliberately cheating (he's a co-owner of the dedi) so this is likely to be a default Wurst feature that he's triggering while just bimbling about.

**Comment by Rammelkast** [comment]
This seems like an issue on the ProtocolLib side. Can you update to the latest ProtocolLib and see if this still happens?

**Comment by xenoflot** [comment]
I downloaded and installed ACR and PL just today.  1.9.5 and 4.5.1 respectively.

**Comment by Rammelkast** [comment]
What server version are you running?

**Comment by xenoflot** [comment]
paper 246 for MC 1.16.3 

Plugins (27): AdvancedPortals, AntiCheatReloaded, AntiXRay, BetterRTP, BetterSleeping3, BuycraftX, Chunky, CoreProtect, CraftBook, DiscordSRV, dynmap*, Essentials, EssentialsSpawn, FastLeafDecay, Graves, GriefPrevention, ItemSoulBind, LuckPerms, Minepacks, PetMaster, ProtocolLib, ServerRestorer, SilkSpawners, Vault, VeinMiner, WorldEdit, WorldGuard

**Comment by Rammelkast** [comment]
ProtocolLib 4.5.1 does not support Minecraft 1.16. You'll need to download the latest dev build as instructed on their Spigot page.
