### ISSUE TITLE
silent-mode not working

### ISSUE THREAD

**Issue by Pingger** [Rammelkast/AntiCheatReloaded#124]
Hi, 

I have the following issue:
The silent-mode is not working. Players are receiving notifications, that they have been flagged. Shouldn't the entire idea of this setting be, that this message is not sent to players?

[config.yml.txt](https://github.com/Rammelkast/AntiCheatReloaded/files/5684877/config.yml.txt)

Version 1.9.5
PaperMC 1.16.4 Build 324

Greetings

**Comment by Rammelkast** [comment]
Silent-mode prevents the anticheat from interfering in gameplay (so no rubberbanding, stopping combat actions). To disable the warning, change the settings in groups.yml.

**Comment by Pingger** [comment]
@Rammelkast You mean like this?!

```
# AntiCheatReloaded configuration file
# Options; WARN, KICK, COMMAND[your command here] or NONE
# To disable warnings or kicking, change WARN and/or KICK to NONE
groups:
- 'Low : 50 : GREEN : NONE'
- 'Medium : 60 : YELLOW : NONE'
- 'High : 75 : RED : NONE'
#- 'Custom : -1 : GREEN : COMMAND[ban %player%;]'
```

Aditonally the documentation for the silent mode is extremely misleading!

```
# If silent mode is on, players will not be stopped when they try to hack, and AntiCheatReloaded will do everything possible to keep them unaware of their rising hack level.
  # However, alerts will still be sent to console and to admins online, and events will still take place.
```

To keep some one unaware, that their hack-level is rising, they must not be informed, that their hack level is rising ... but they are informed, when silent-mode is enabled...

Greetings

**Comment by Rammelkast** [comment]
Thanks for reporting this, the explaination is indeed a bit confusing. Yes, that groups.yml should disable any cheat warnings.

**Comment by Pingger** [comment]
Unforuntaly it does not. Several users have asked, why they were flagged for cheating (in most cases an obvious (for a human) false-positive because of a server lag-spike)

**Comment by Rammelkast** [comment]
Can you send me the message players receive?

**Comment by Pingger** [comment]
![Uploading image.png…]()

**Comment by Rammelkast** [comment]
Have you reloaded your config?

**Comment by Pingger** [comment]
How do you mean "Have I reloaded my config?"

I do a server reboot every 6 hours, because Minecraft Servers tend to loose performance when they are running too long,
but because ACR quite often kick people out of nowhere, where they are obviously not hacking, I have currently disabled it until the issue is resolved

**Comment by Rammelkast** [comment]
Can you send me your config.yml?

**Comment by Pingger** [comment]
> 
> 
> Can you send me your config.yml?

See Opening Post! (the '.txt'  is just so github allows me to upload)

Alternatively here all my configs:

[zip.zip](https://github.com/Rammelkast/AntiCheatReloaded/files/5742152/zip.zip)

**Comment by Rammelkast** [comment]
Does this issue still occur for you with ACR 1.9.6?

**Comment by Pingger** [comment]
No idea ... after all this time I already scrapped the plugin entirely from my server ...

**Comment by Rammelkast** [comment]
Closed - Failed to verify.
