### ISSUE TITLE
Bugs, speed/fly on slabs

### ISSUE THREAD

**Issue by MIsiuwa** [Rammelkast/AntiCheatReloaded#125]
Constantly detects incorrect speed or fly on slabs. Pleas fix it

**Comment by Rammelkast** [comment]
What minecraft version are you running?

**Comment by Rammelkast** [comment]
Closed due to lack of response and failure to verify.

**Comment by RobinRMC** [comment]
I can confirm this. I've got those false positives too and I therefore disabled the checks for it. Would be nice if it's fixed. :)

Reproduction: try running on and off slabs, you will get spammed with false positives.
