### ISSUE TITLE
Skript integration does not work properly.

### ISSUE THREAD

**Issue by MajkCzech** [Rammelkast/AntiCheatReloaded#126]
Hello,
we are running your Anti-Cheat plugin on our server with skript installed too. But if we want to run skript command, the anticheat will popup that we are spamming, but that's not true. If it is some problem with your plugin or skript, we don't actually know. 

Thanks if you will responde to this issue and have a nice day,
MajkCzech

**Comment by Rammelkast** [comment]
Can you show me a bit of the skript you are running?

**Comment by Rammelkast** [comment]
Closed - lack of response.
