### ISSUE TITLE
Noclip bypass

### ISSUE THREAD

**Issue by liulihaocai** [Rammelkast/AntiCheatReloaded#127]
https://youtu.be/K5e0bQvsyK8
just watch the vid
My friend find that can bypass
fix this plz :)

**Comment by Rammelkast** [comment]
Closed - could not verify with latest LiquidBounce and ACR.

**Comment by ENDER1355** [comment]
> Closed - could not verify with latest LiquidBounce and ACR.

PS: Loyisa's test server is garbage, you have to make your own private or public ACR-only test server.
