### ISSUE TITLE
HopFly Bypass

### ISSUE THREAD

**Issue by liulihaocai** [Rammelkast/AntiCheatReloaded#128]
This script is used to bypass AAC in redesky LOL
but i found it can bypass ACR

script plz use in LiquidBounce b72
[HopFly.zip](https://github.com/Rammelkast/AntiCheatReloaded/files/5836557/HopFly.zip)
dont send this script to anyone else

video
https://www.mediafire.com/file/wrqtscktc9zmnv4/2021-01-19_22-44-09.mp4/file

**Comment by Rammelkast** [comment]
Fixed.

**Comment by ENDER1355** [comment]
This bug can be reachived with NCP Fly and Timer in Liquidbounce, it will float you, but then vanilla kick.
