### ISSUE TITLE
Setting check.elytrafly to true doesn't give exemptions to elytrafly checks

### ISSUE THREAD

**Issue by joycourier** [Rammelkast/AntiCheatReloaded#131]
Hello, please check the screenshots

I'm not sure whether this is an issue caused by my server's specific plugin setup or not but the perm for bypassing elytrafly checks doesn't seem to be working for this gentleman

![javaw_pGp66IoNDt](https://user-images.githubusercontent.com/42023242/106753653-da763300-6623-11eb-94ea-c5dd6fa448dd.png)
![javaw_fstVrm2I0C](https://user-images.githubusercontent.com/42023242/106753661-dd712380-6623-11eb-86c4-af81118fdf5b.png)

**Comment by Rammelkast** [comment]
This was due to a code issue, not something on your side. It's now fixed in the code and will be patched in the next release.
