### ISSUE TITLE
Wiki????

### ISSUE THREAD

**Issue by SimmsRyan97** [Rammelkast/AntiCheatReloaded#136]
Hey I left 2 messages on Spigot asking for a wiki on how to setup ACR as it seems like everyone on my server can pretty much bypass all checks even though they all the the permissions for the checks. Please it'd be nice if you responded on Spigot and also maybe had some sort of guide.

**Comment by Rammelkast** [comment]
Hi, as of now there is a wiki planned for the 2.0 release of ACR. As for the permission issues, if a player has the permission for a check it means they're allowed to bypass it.
