### ISSUE TITLE
Flags for Scaffold when building and placing blocks under you

### ISSUE THREAD

**Issue by CookieGuy123** [Rammelkast/AntiCheatReloaded#138]
When you build up and place blocks under you to stack up, it flags you for scaffold and you have to place the blocks every 2 seconds to not get flagged. I have some players on my server who get false banned for it and it should be fixed immediately.

Please fix it 😀 

**this is a great anticheat** 😃

**Comment by Rammelkast** [comment]
Assuming to be fixed as of 5f1dc37.
