### ISSUE TITLE
ProtocolLib Issue

### ISSUE THREAD

**Issue by LucasMucGH** [Rammelkast/AntiCheatReloaded#140]
I discovered the following issue using this anti-cheat:

https://github.com/dmulloy2/ProtocolLib/issues/1121#issue-837999970

I know it looks like a ProtocolLib Issue, but it only appears when using BOTH AntiCheatReloaded AND ProtocolLib. When using ProtocolLib alone it is working fine. So maybe the issue is on the AntiCheatReloaded site.

**Comment by Geolykt** [comment]
This is very likely a java version issue with protocollib; I doubt it is anything that is fixable on ACR's part

**Comment by LucasMucGH** [comment]
Ok, thank you. I will leave it open on both sides until it is resolved, if you don't mind :)

**Comment by Rammelkast** [comment]
This is indeed most likely a ProtocolLib issue.
