### ISSUE TITLE
Airjump

### ISSUE THREAD

**Issue by RedWay228** [Rammelkast/AntiCheatReloaded#147]
cheat: Flux b13
link: https://www.mediafire.com/file/lp8e9s6hoayr1hz/flux-b13.rar/file
server: tree.ac
video: https://www.mediafire.com/file/qbiqwjbzbnx4ypr/2021-05-23_14-58-12.mp4/file

**Comment by ENDER1355** [comment]
tree.ac's ACR is broken, it is a bug probably caused by AAC or NCP, I cannot reproduce it again.

**Comment by ENDER1355** [comment]
> cheat: Flux b13
> link: https://www.mediafire.com/file/lp8e9s6hoayr1hz/flux-b13.rar/file
> server: tree.ac
> video: https://www.mediafire.com/file/qbiqwjbzbnx4ypr/2021-05-23_14-58-12.mp4/file

Also, remove the link of Flux b13, it's paid, you are linking to a pirated client which is not okay, Flux is not free.
