### ISSUE TITLE
AFK pools, Honey Blocks and Soul sand

### ISSUE THREAD

**Issue by JericNisperos** [Rammelkast/AntiCheatReloaded#148]
The plugin is detecting false reports about Spider on Soul Sand AFK, where you can add a water above soul sand and stand above it for anti-afk. We are allowing these on our server. Additionally, AFK Pools are detecting as More Packets and Honey Blocks can't be used in a parkour as the players will be stuck from the Honey Blocks. Is there any option from the config that I can tweak for this? Thank you.

Btw. Currently using latest version of ACR and the MC Version is 1.16.5. Client Version is 1.16.5 and the Launcher is Paper, latest version as well.

**Comment by Rammelkast** [comment]
Should be improved as of 9d97803
