### ISSUE TITLE
tp bug

### ISSUE THREAD

**Issue by ENDER1355** [Rammelkast/AntiCheatReloaded#151]
1. if you get setbacked while on a soul sand, you'll get teleported forwards

**Comment by ENDER1355** [comment]
high priority?

**Comment by Rammelkast** [comment]
Hi, can you make a video since I cant get this to replicate exactly.

**Comment by ENDER1355** [comment]
> Hi, can you make a video since I cant get this to replicate exactly.

Ok

**Comment by ENDER1355** [comment]
> Hi, can you make a video since I cant get this to replicate exactly.

It was a bug caused by tree.ac which is fixed now, however, there is another tp bug whose teleport speed doesn't flag when standing on a soul sand.

**Comment by ENDER1355** [comment]
Invalid issue
