### ISSUE TITLE
Using Lunar Client's FlyBoost (requires creative) will get you kicked by ACR

### ISSUE THREAD

**Issue by ENDER1355** [Rammelkast/AntiCheatReloaded#157]
Plugins: ProtocolLib and ACR
Server: My own fresh server
How to reproduce:
1. Download LC and launch LC
2. Go on a server with ACR, or make your server with ACR
3. Give yourself creative, or ask someone to give creative, or get creative by dying (Bedwars)
4. Use flyboost feature
5. Get kicked

**Comment by Rammelkast** [comment]
ACR is built for Vanilla clients. Any features not Vanilla (like LC's modified flight speed) will not be supported.

**Comment by ENDER1355** [comment]
> ACR is built for Vanilla clients. Any features not Vanilla (like LC's modified flight speed) will not be supported.

Oh ok.
