### ISSUE TITLE
It doesn't even work

### ISSUE THREAD

**Issue by TangledWiresYT** [Rammelkast/AntiCheatReloaded#164]
So I was looking for a free anti-cheat for my server and came across this. I then installed it and found that it didnt work. I actually downloaded meteor client to test this and nothing. No kicks no bans.

**Comment by Rammelkast** [comment]
You need ProtocolLib as well. Also, make sure you are not opped.

**Comment by TangledWiresYT** [comment]
I had already deopped myself and also installed ProtocolLib and I couldn't make it work

**Comment by Rammelkast** [comment]
Do you have no console errors? Do ProtocolLib and ACR show up in /plugins?

**Comment by TangledWiresYT** [comment]
There are no console errors and both plugins are there.

**Comment by Rammelkast** [comment]
When performing the /plugins command, do ProtocolLib and ACR show up in green?

**Comment by TangledWiresYT** [comment]
Yes both are green

**Comment by TangledWiresYT** [comment]
Both plugins show up in green

**Comment by TangledWiresYT** [comment]
And the other ones i installed: Essentials, WorldEdit, etc

**Comment by TangledWiresYT** [comment]
I didnt have any other anti-cheat installed but its fine, i dont think my server will go public anytime soon

**Comment by Rammelkast** [comment]
Did you deop yourself before testing?
