### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by x7eco** [Rammelkast/AntiCheatReloaded#165]
Hi, there's a bug inside plugin. When player accepts a quest then leave server and reconnect, it'll instantly jump up to next stage of the quest and its even possible to complete the quest this way.

**Comment by Rammelkast** [comment]
Hi, can you explain this further?

**Comment by x7eco** [comment]
I created an mpc quest which, when a person activates, gets lost and
reconnects to the server automatically, so he can complete tasks by
returning and reconnecting


pi 6. 8. 2021 o 15:12 Rammelkast ***@***.***> napísal(a):

**Comment by Rammelkast** [comment]
Can you send a video of the issue?

**Comment by Rammelkast** [comment]
Closed - no response.
