### ISSUE TITLE
kick msgs

### ISSUE THREAD

**Issue by Aadi-mone** [Rammelkast/AntiCheatReloaded#176]
instead of Kicked for unfair advantage message can we do like 

You have been kicked for cheating, (cheat ex: flight)

I used this : &7Kicked for cheating, %check%

but it's not working. 

help please :)

**Comment by mcshept** [comment]
Check must be replaced with reason i guess

**Comment by Aadi-mone** [comment]
yes, but instead of that %check% it self comes after a kick :/
