### ISSUE TITLE
Swimming in kelp in 1.17.1 triggers AirFlight

### ISSUE THREAD

**Issue by codeHusky** [Rammelkast/AntiCheatReloaded#177]
Players are triggering airflight on my server from swimming in kelp on 1.17

This server is running Airplane version git-Airplane-87 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 002f470 on HEAD)

On ACR 1.9.8

**Comment by Rammelkast** [comment]
Seems to be fixed since 9d97803
