### ISSUE TITLE
Elytra detection

### ISSUE THREAD

**Issue by Augustin37** [Rammelkast/AntiCheatReloaded#18]
Hello, this issue is about the elytra flight considered like a cheat from the plugin. I made a video to make it clearer
[![Alt text](https://img.youtube.com/vi/3eWJy9GRezU/maxresdefault.jpg)](https://www.youtube.com/watch?v=3eWJy9GRezU)

You also asked me to give you the plugin logs, here there are:
```java
[INFO|7:09:20]: Testation ascended 8 times in a row (max = 8) 
[INFO|7:09:24]: Testation ascended 8 times in a row (max = 8) 
[INFO|7:09:34]: Testation's speed was too high 3 times in a row (max=3, speed=0.2668666990175552, max speed=0.25) 
```

Thank you :)

**Comment by Rammelkast** [comment]
Can you check if this still happens with 1.5.3-ALPHA (located in the Releases tab)?

**Comment by Augustin37** [comment]
I just checked, it still makes it. I get catch only when I try to ascend; when I just glide without trying to get up, it works
