### ISSUE TITLE
getting kick without even using hacking client

### ISSUE THREAD

**Issue by Swift12gaming** [Rammelkast/AntiCheatReloaded#185]
when using elytra it detect as if we are using flying , elytra hack and stops it & kicked them from the server so pls fix it

**Comment by Swift12gaming** [comment]
im using 1.10.0 acr
im using default acr config
and there is no error in logs

**Comment by Ali00035** [comment]
> im using 1.10.0 acr im using default acr config and there is no error in logs

enable debug mode in config.yml

**Comment by Rammelkast** [comment]
Closing - no response.
