### ISSUE TITLE
Pillaring Up Triggers "Tried to Climb Air"

### ISSUE THREAD

**Issue by blockswerker** [Rammelkast/AntiCheatReloaded#188]
As the title says, vanilla players pillaring upwards with blocks trigger this `Failed Flight - Tried to climb air` after placing 2 blocks. I'm not sure what to disable or change to allow it, setting "airClimb" to false has no effect.

**Comment by wsquarepa** [comment]
Same issue here, It's very annoying to the players on my server as they can no longer pillar upwards

**Comment by Rammelkast** [comment]
Can you enable debug-mode and send a video of it happening?

**Comment by Rammelkast** [comment]
Should be fixed in the latest CI build - please message if issue persists.
