### ISSUE TITLE
Can ACR auto-ban at the 2nd time after the hacker had been kicked by ACR for cheating?

### ISSUE THREAD

**Issue by hyhcrh** [Rammelkast/AntiCheatReloaded#191]
Can ACR auto-ban at the 2nd time after the hacker had been kicked by ACR for cheating?
I have a server using ACR, but I can't keep online for all day long.
So I hope the author can let op or server host have a choice that whether the hacker should be auto-banned at the 2nd time for cheating.
Now the spamming (chat / commands) have already had this choice, so I hope other "real cheating" can have the same choice.
Thanks!

**Comment by wsquarepa** [comment]
you can add `COMMAND[ban %player% Hacking is not enabled on this server]` in groups.yml for your second group...
