### ISSUE TITLE
ALERT in lang.yml never getting fired.

### ISSUE THREAD

**Issue by vlOd2** [Rammelkast/AntiCheatReloaded#196]
What I expected ACR to do: Whenever a player's group is change, to fire the ALERT message.
What happend: nothing
AntiCheatReloaded version: Based on [84ddce8](https://github.com/Rammelkast/AntiCheatReloaded/commit/ebfd8f69af911829aa93fd79f2a6c98582a00e84)
Server: Spigot 1.12.2
ProtocolLib: 4.7.0

I have disable-broadcast set to false but it's still not working.
Somebody help?

**Comment by Rammelkast** [comment]
Can you show me your groups.yml?

**Comment by Rammelkast** [comment]
Closing - no response.
