### ISSUE TITLE
Make the failed check message not hard coded.

### ISSUE THREAD

**Issue by vlOd2** [Rammelkast/AntiCheatReloaded#197]
The failed check message is hard coded.
Can't that be change to made available in the lang.yml, so the ALERT_PREFIX can be removed?

Something like:
ALERT_CHECK: '&f%player% failed %check% &6(x%violations%) &8|&7 type: %type%, ping: %ping%ms, tps: %tps%'

AntiCheatReloaded version: Based on [84ddce8](https://github.com/Rammelkast/AntiCheatReloaded/commit/ebfd8f69af911829aa93fd79f2a6c98582a00e84)
Server: Spigot 1.12.2
ProtocolLib: 4.7.0

**Comment by ElmEditor** [comment]
[reply]
