### ISSUE TITLE
KillAura bot positioning

### ISSUE THREAD

**Issue by EncryptSL** [Rammelkast/AntiCheatReloaded#20]
Please repair the bot. Detection KillAura.
Instead of the bot behind the player.
So that the front and when the player stands on the spot to still be over and constantly checked it and badgered and spun around player.

Here's the thing that killaura can not detect this in your programming if you understand.

Be just fine I walk with killaura and nothing's no kick.

I'd like there to fix the tab names bots occupied only one top slot in tab ..

Bot must constantly be in front of a player when he walks. Although the fighting has to be a leading bot.

Thx for repair.

**Comment by MarvanCZ** [comment]
Rammelkast - 
Maybe they were too good adjustment in such a form. Of course it's up to you. But I think it would be even better.
Look.

https://www.youtube.com/watch?v=hdshzNMIlEE&feature=youtu.be

**Comment by Rammelkast** [comment]
Bot positioning seems broken (need info on this), moved to medium priority.

**Comment by Rammelkast** [comment]
See #50.

**Comment by Rammelkast** [comment]
Moved to #52
