### ISSUE TITLE
Riptide Trident False Positive

### ISSUE THREAD

**Issue by wsquarepa** [Rammelkast/AntiCheatReloaded#204]
Using a riptide trident flags you for flight and speed.
**Haven't tested with elytra** but without elytra, it does flag you.

Minecraft: 1.18.1
ACR 1.10.2
Configs Default except FastPlace is disabled
ProtocolLib 4.7.0

**Comment by Rammelkast** [comment]
I can not replicate this with 1.11.0-PRE, considering fixed.
