### ISSUE TITLE
When startup and shutdown it gives off an error.

### ISSUE THREAD

**Issue by ItzVaio** [Rammelkast/AntiCheatReloaded#212]
When i startup my server (hosting is on aternos), It will give me a error. And i'm running the bukkit version of ACR, I switched to the spigot version right now.

2GB RAM Server.
Spigot MC 1.18.1
ProtocolLib 4.7.0 installed.

The Spigot Version works, But the bukkit version just gives you a lot of errors at server startup, and server shutdown.

**Comment by ItzVaio** [comment]
Spigot version was working now gives off a error. 
![image](https://user-images.githubusercontent.com/73048123/147858391-e4fd0e50-d1ee-4847-93ca-44d16b2404ff.png)
![image](https://user-images.githubusercontent.com/73048123/147858404-757ad4c0-9a1c-4e07-8e9a-a3da11f4ce93.png)

**Comment by Rammelkast** [comment]
This was fixed in 7842153 and has to do with Spigot 1.18.1 suddenly removing a feature. The latest dev build will have these fixes. (https://ci.rammelkast.com/job/AntiCheatReloaded/lastSuccessfulBuild/com.rammelkast.anticheatreloaded$AntiCheatReloaded/)
