### ISSUE TITLE
Moving in Kelp False Positive

### ISSUE THREAD

**Issue by wsquarepa** [Rammelkast/AntiCheatReloaded#215]
**Steps to reproduce:**
1. Move in waterlogged kelp in a 1 by 1 space (To make sure you are **in** the kelp)

This is very annoying to my players as they are being kicked for flying because they are building a bubble column using kelp

---
Minecraft: 1.18.1
Version: `git-Paper-140 (MC: 1.18.1)` (PaperMC)
ACR 1.10.2
Fully Default Configs
ProtocolLib 4.7.0

There are no protocol hacks installed

**Comment by Rammelkast** [comment]
Please try the latest ProtocolLib and ACR versions.

**Comment by wsquarepa** [comment]
Sincere apologies, I provided the incorrect ACR version. I'm using ACR 1.10.3.
I believe ProtocolLib is updated to the latest version (4.7.0).
