### ISSUE TITLE
False positive on bedrock players [Geyser Mc]

### ISSUE THREAD

**Issue by NixonXC** [Rammelkast/AntiCheatReloaded#217]
whenever a bedrock player tries to play in the server the anti cheat thinks they are hacking I am using GeyserMC

**Comment by Rammelkast** [comment]
Do you have Floodgate installed on the server?

**Comment by NixonXC** [comment]
Yes

**Comment by Rammelkast** [comment]
Does floodgate show up in /pl? And do you use anything like BungeeCord?

**Comment by NixonXC** [comment]
Yes it shows up in /pl and no I don't have anything installed like BungeeCord but different worlds with multiverse

**Comment by Rammelkast** [comment]
What checks are falsing?

**Comment by NixonXC** [comment]
Movement and fall ones
