### ISSUE TITLE
[BYPASS]

### ISSUE THREAD

**Issue by RedWay228** [Rammelkast/AntiCheatReloaded#219]
client: Liquidbounce b73 1.12.2
video: 
I tested ACR 1.11.0-PRE

**Comment by Rammelkast** [comment]
Could you please use Streamable for the videos instead of MediaFire, since it doesn't work for me.

**Comment by RedWay228** [comment]
ok

**Comment by RedWay228** [comment]
https://staging.streamable.com/4wquwq

**Comment by RedWay228** [comment]
Did you manage to reproduce bypass?

**Comment by Rammelkast** [comment]
Yes. The default magic.yml just allows too much leniency when leaving boats. I changed the default value (not sure if this has been committed yet)
