### ISSUE TITLE
bypasses

### ISSUE THREAD

**Issue by ghost** [Rammelkast/AntiCheatReloaded#223]
https://streamable.com/udxmjt
:trollface: settings for speed in vid and https://updown.link/rB?pt=YmpNNFRYRkdaalJwYkV0aWJIRTBTa0p5T0hocVp6MDlPdlRjQm9jaDlQazYvTElJSU9KRDBIcz
for the download.
Step mode aac335, aac339. Work fine.
Jesus mode NCP, normal works too but for normal u have to hold the spacebar.
Spider mode aac336. Works fine kinda cool the way it works with slightly glitching into the block to bypass.
Also why tf is there literally no speed checks at all in liquid I will go into the water and I will be able to go like 75 bps so u should prob make a speed check-in water.
The NoSlowDown check is due for a rewrite too cause I've literally never flagged that unless I was using NCP no slow and blocking a sword nothing else has ever flagged that check personally from my testing I've done on it.

**Comment by Rammelkast** [comment]
What ACR version was used?

**Comment by notperry12345678902** [comment]
> What ACR version was used?

1.10.3 I can use dev versions if u want
