### ISSUE TITLE
[BYPASS] BoatFly

### ISSUE THREAD

**Issue by RedWay228** [Rammelkast/AntiCheatReloaded#224]
client: FDPClient 1.8.9 
video: https://staging.streamable.com/gs81h9
src: https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/BoatJump.kt#L99

**Comment by RedWay228** [comment]
@Rammelkast you can send me a friend request so that I can send you a link to viaforge?

**Comment by RedWay228** [comment]
Nower#1112

**Comment by Rammelkast** [comment]
Did you use the latest github version of the magic.yml file?

**Comment by RedWay228** [comment]
Yes
