### ISSUE TITLE
huge badpackets issue

### ISSUE THREAD

**Issue by ghost** [Rammelkast/AntiCheatReloaded#225]
after commit 031e7b145b410500b3aef1594decb55022cce9b7 whenever u get flagged back by badpackets it teleports u down to y 0 so yeah that should probably be fixed asap

**Comment by notperry12345678902** [comment]
I can provide a video if needed/wanted

**Comment by ItzVaio** [comment]
> I can provide a video if needed/wanted

that actually is needed to show proof

**Comment by notperry12345678902** [comment]
https://streamable.com/iosffs
(Go I think at least over 5 blocks from the ground and flag badpackets and u will get tped to y 0 idk if it's exactly 5 blocks over the ground haven't bothered to measure yet).
