### ISSUE TITLE
NPE when logging out

### ISSUE THREAD

**Issue by SevenX159** [Rammelkast/AntiCheatReloaded#23]
Every time someone log off, or get kicked because of cheat, i got this error
https://gyazo.com/5abf396655ff083730494b11bc6dd26f
EDIT: After a moment, normals player don't have this error when log off, but admins still have it

**Comment by Rammelkast** [comment]
Please try this with the latest version (1.5.4, availible from "Releases"). If this issue persists, please reopen this ticket.
