### ISSUE TITLE
ACR missing config settings for all cheats

### ISSUE THREAD

**Issue by phigiaon** [Rammelkast/AntiCheatReloaded#235]
[https://media.discordapp.net/attachments/947639491361919029/952588912449167370/20220313_082808.png](url) 
ACR version: 1.10.3
Spigot 1.18.1
ProtocolLib: 4.8.0
No Protocol hack
I cant seem to get ACR to work properly and it keep spewing a lot of garbage onto my console

**Comment by gggggggggggggggggggggggggggggg123** [comment]
i am having the same issue rn, can you msg me if you have found a solution

**Comment by Mizak412** [comment]
Same here please help!

**Comment by jorisdigitalREAL** [comment]
same
