### ISSUE TITLE
Operator

### ISSUE THREAD

**Issue by AKAGPIXEL** [Rammelkast/AntiCheatReloaded#237]
Hello I will install The Anti In A weeks on My new server Can You Tel Me something You said only Hacker gets banned Can Operators get banned When the use fly /give /to or auto click pls reply I don't want my server to malfunction
I am using the software Called Aternos.org To make the server Pls Reply fast

**Comment by RealmKebab** [comment]
no.
they dont get banned
only people that are cheating without op get banned
