### ISSUE TITLE
GhostHand check

### ISSUE THREAD

**Issue by MC-Admin40** [Rammelkast/AntiCheatReloaded#24]
Factions 1.11 server but main issue is that i saw a player that was able to reach though barrier blocks to turn off a daylight sensor.  The barrier enclosed room was inaccessible to players so they probably was able to phase through barrier blocks as well.  There were buttons beside the door but they were on the inside and the doors were iron, so no way inside, only out and nobody was near the area to have opened the room from the inside.

**Comment by Rammelkast** [comment]
This is referred to as 'ghosthand', a hackclient feature which allows you to interact with blocks through other blocks.

I'll take a look at it.

**Comment by Rammelkast** [comment]
See #50.

**Comment by Rammelkast** [comment]
I have created the check and will now focus on testing for false positives.

**Comment by Rammelkast** [comment]
Added with commit fec1286
