### ISSUE TITLE
SpeedHack bypass.

### ISSUE THREAD

**Issue by Fint1841** [Rammelkast/AntiCheatReloaded#244]
https://youtu.be/ycN4lB4dpvg.

**Comment by RedWay228** [comment]
I can't reproduce bypasses on ACR 1.11 https://staging.streamable.com/kf119d

**Comment by Fint1841** [comment]
Bypass ACR 1.10.3 latest. Plugin from spigotmc.

**Comment by RedWay228** [comment]
I downloaded the latest release from here https://ci.rammelkast.com/job/AntiCheatReloaded/lastBuild/

**Comment by RedWay228** [comment]
![2022-05-17_23-31-39](https://user-images.githubusercontent.com/76217902/168874823-cc2680ca-d635-4c65-9812-cd34a235a92a.png)
