### ISSUE TITLE
WaterWalk detection not working on 1.11

### ISSUE THREAD

**Issue by MarvanCZ** [Rammelkast/AntiCheatReloaded#25]
Hello Rammelkast. WaterWalk detection does not work. To version 1.11 
Successfully but it works to version 1.10 
Tested on wolfram and Wurst.

**Comment by Rammelkast** [comment]
Can you record a video?

**Comment by Rammelkast** [comment]
I cannot reproduce this bug, please reopen the ticket when you have a video,
