### ISSUE TITLE
it is NOT compatible with slimefun and some other plugins

### ISSUE THREAD

**Issue by StarchierOrb** [Rammelkast/AntiCheatReloaded#39]
it will kick player when the player use the slimefun item XD

**Comment by Rammelkast** [comment]
Can you be more clear?

**Comment by StarchierOrb** [comment]
just when my player using slimefun items like flying bag to fly,the plugin will warn the player not to fly and kick him!

**Comment by Notoh** [comment]
This can be easily fixed by creating something along the lines of a simple API to add exemptions to certain cheats temporarily, and it can be called by the plugin being flagged if ACR exists.

**Comment by Rammelkast** [comment]
See #50.

**Comment by Rammelkast** [comment]
As @Notoh noted, this is more of an issue for the developer of SlimeFun. I might look in to this later, but as of now the only solution would be to ask the author of SlimeFun to implement ACR API support or do it yourself.
