### ISSUE TITLE
AntiCheatReloaded  kill aura problem

### ISSUE THREAD

**Issue by omeryayinci** [Rammelkast/AntiCheatReloaded#44]
kill aura detection problem please update

**Comment by Rammelkast** [comment]
Can you describe the issue?

**Comment by omeryayinci** [comment]
kill aura hack in the egg wars game

**Comment by Rammelkast** [comment]
I don't get it, do you have a video?

**Comment by omeryayinci** [comment]
Unfortunately there is no minecraft egg wars game. orda kill aura hack i anti cheat reload plugin does not notice even if the game is over error this kill aura hack prevent
