### ISSUE TITLE
AntiCheatReloaded  Freecam hex

### ISSUE THREAD

**Issue by omeryayinci** [Rammelkast/AntiCheatReloaded#45]
kill aura and freecam can not detect kill aura is occasionally perceived but freecam never sees men can fly and break the world emergency help! and 
blink does not prevent hex

**Comment by Rammelkast** [comment]
Could you explain the problem a bit clearer?

**Comment by Rammelkast** [comment]
So - if i get you correctly;
- The KillAura check takes too long to find out that a user is using killaua
- People can break blocks at far distances with freecam

is this correct?

**Comment by omeryayinci** [comment]
What do you say I can video about cheating for you to better understand ?

5 Ara 2017 ÖS 8:32 tarihinde Rammelkast <notifications@github.com> yazdı:

So - if i get you correctly;

  *   The KillAura check takes too long to find out that a user is using killaua
  *   People can break blocks at far distances with freecam

is this correct?

**Comment by Rammelkast** [comment]
A video would be helpful yes.

**Comment by Rammelkast** [comment]
Due to the lack of response I am closing this issue.
