### ISSUE TITLE
Not getting banned on second time hacking!

### ISSUE THREAD

**Issue by Vemize** [Rammelkast/AntiCheatReloaded#5]
I downloaded a hack client to see if it works and when i used the hacks i did it like 5 times and i wasnt getting banned after the 2nd time

**Comment by Rammelkast** [comment]
What do you mean, you're not very clear...
Also, this plugin doen not auto-ban.

**Comment by Vemize** [comment]
Oh so they don't get auto banned if they keep hacking but does it alert ops? I haven't edited config or anything so if I can do something to change this can you please hell

**Comment by Rammelkast** [comment]
It does alert OP's, yes.
