### ISSUE TITLE
Allow for backwards compatibility

### ISSUE THREAD

**Issue by Rammelkast** [Rammelkast/AntiCheatReloaded#56]
The goal is to support the following versions:

- [ ] 1.9.x
- [ ] 1.10.x
- [ ] 1.11.x
- [ ] 1.12.x
- [x] 1.13.x
- [x] 1.14.x
- [x] 1.15.x

**Comment by Rammelkast** [comment]
Added backwards compatibility for 1.14 and 1.13.

**Comment by EncryptSL** [comment]
You have good idea, but i think this is only create more troubles, because Anti Cheat work different on Survival with SlimeFun & Vanilla survival and minigames, you must test on all sides.

**Comment by Rammelkast** [comment]
I think I understand what you mean, but as of now I assume other plugins create exceptions by hooking into ACR, not the other way around. I might add compatibility with SlimeFun, McMMO, etc. myself later, but not now.

**Comment by EncryptSL** [comment]
Another point about false positives, on superflat map anticheat have less false positives then on Survival map.

**Comment by Rammelkast** [comment]
Fair point. I'll have a look at improving my testing methods.
