### ISSUE TITLE
Chat doesnt allow unicode (Ä / Ö / Ü / ä / ö / ü)

### ISSUE THREAD

**Issue by MaxOette** [Rammelkast/AntiCheatReloaded#59]
Hello!
Great plugin!
But i have a Problem: Im from Germany so we use the letters ä, ü, ö and ß in our normal conversations.
But if someones writes that in Chat and presses enter, plugin says "Unicode Chat is not allowed" or so...

is there a way to disable this?

**Comment by Rammelkast** [comment]
Hi,
You can disable this check by opening config.yml and adding CHAT_UNICODE under disabled-checks.

**Comment by MaxOette** [comment]
> Hi,
> You can disable this check by opening config.yml and adding CHAT_UNICODE under disabled-checks.

Cool thanks. I have another question: below this "disabled-checks" section there is the possibility to disable worlds. If i make e.g. the entry "lobbyworld" there, what is happening then? Wont the plugin check any cheaters in "lobbyworld" or will it only ignore the flags listed in disabled-checks?

**Comment by Rammelkast** [comment]
World listed in the disabled worlds list will be completely exempt from all checks and thus ACR will not check players in those worlds.

**Comment by MaxOette** [comment]
thank you. Now i found another problem: I (as admin) always get messages "PLAYERNAME failed fast healing...." but the problem is, they are not cheating. Their food bar is full and this is why they regenerate health fast for i think about 2.5s. But in the config files etc. i cannot find the flag FAST_HEAL to change the value a little bit... can you help me finding it?Thank you
-------- Ursprüngliche Nachricht --------Von: Rammelkast <notifications@github.com> Datum: 03.04.20  22:44  (GMT+01:00) An: Rammelkast/AntiCheatReloaded <AntiCheatReloaded@noreply.github.com> Cc: MaxOette <maxoette@mail.de>, Author <author@noreply.github.com> Betreff: Re: [Rammelkast/AntiCheatReloaded] Chat doesnt allow unicode (Ä / Ö / Ü / ä / ö / ü) (#59) 
Worlds listed in the disabled worlds list will be completely exempt from all checks and thus ACR will not check players in those worlds.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Rammelkast/AntiCheatReloaded/issues/59#issuecomment-608649364",
"url": "https://github.com/Rammelkast/AntiCheatReloaded/issues/59#issuecomment-608649364",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Rammelkast** [comment]
As of now there is no configuration option for fastheal. However I am very interested since this false positive has never been reported. Can you show me the result of /gc and tell me what server and version you are running?

**Comment by MaxOette** [comment]
my server is spigot 1.14.4cant send /gc because the photo file is too big but there dont seem to be errors
-------- Ursprüngliche Nachricht --------Von: Rammelkast <notifications@github.com> Datum: 06.04.20  16:49  (GMT+01:00) An: Rammelkast/AntiCheatReloaded <AntiCheatReloaded@noreply.github.com> Cc: MaxOette <maxoette@mail.de>, Author <author@noreply.github.com> Betreff: Re: [Rammelkast/AntiCheatReloaded] Chat doesnt allow unicode (Ä / Ö / Ü / ä / ö / ü) (#59) 
As of now there is no configuration option for fastheal. However I am very interested since this false positive has never been reported. Can you show me the result of /gc and tell me what server and version you are running?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Rammelkast/AntiCheatReloaded/issues/59#issuecomment-609841389",
"url": "https://github.com/Rammelkast/AntiCheatReloaded/issues/59#issuecomment-609841389",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Rammelkast** [comment]
Is there no lag whatsoever? So a TPS of 19 or higher?

**Comment by MaxOette** [comment]
tps is 20 and it only lags when the server is saving its worlds every 4 hours or so
-------- Ursprüngliche Nachricht --------Von: Rammelkast <notifications@github.com> Datum: 07.04.20  12:41  (GMT+01:00) An: Rammelkast/AntiCheatReloaded <AntiCheatReloaded@noreply.github.com> Cc: MaxOette <maxoette@mail.de>, Author <author@noreply.github.com> Betreff: Re: [Rammelkast/AntiCheatReloaded] Chat doesnt allow unicode (Ä / Ö / Ü / ä / ö / ü) (#59) 
Is there no lag whatsoever? So a TPS of 19 or higher?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Rammelkast/AntiCheatReloaded/issues/59#issuecomment-610313697",
"url": "https://github.com/Rammelkast/AntiCheatReloaded/issues/59#issuecomment-610313697",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MaxOette** [comment]
Hello. Sorry for the late respone i think i screwed something up... my last mail returned to ne xDWell my TPS is 20.0 and my server only lags when it is saving his world files every few hours. But additionally to this "FastHeal"-Issue i found another problem: ACR sometimes says "PLAYER failed Blink" but i dont know what this means...i hope you can help meMaxOette
-------- Ursprüngliche Nachricht --------Von: Rammelkast <notifications@github.com> Datum: 07.04.20  12:41  (GMT+01:00) An: Rammelkast/AntiCheatReloaded <AntiCheatReloaded@noreply.github.com> Cc: MaxOette <maxoette@mail.de>, Author <author@noreply.github.com> Betreff: Re: [Rammelkast/AntiCheatReloaded] Chat doesnt allow unicode (Ä / Ö / Ü / ä / ö / ü) (#59) 
Is there no lag whatsoever? So a TPS of 19 or higher?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Rammelkast/AntiCheatReloaded/issues/59#issuecomment-610313697",
"url": "https://github.com/Rammelkast/AntiCheatReloaded/issues/59#issuecomment-610313697",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Rammelkast** [comment]
For the blink issues, open magic.yml and change BLINK_PACKET to 30 and BLINK_AVERAGE_PING to around 200 or so.
