### ISSUE TITLE
There is a lot of false positives

### ISSUE THREAD

**Issue by XmatrixX97** [Rammelkast/AntiCheatReloaded#60]
**Here I leave a log of the anticheat**
___________
[anticheat.log](https://github.com/Rammelkast/AntiCheatReloaded/files/4432783/anticheat.log)
___________
![imagen](https://user-images.githubusercontent.com/29832137/78464578-7a3ff900-76c1-11ea-81db-79a8f6458c0d.png)
![imagen](https://user-images.githubusercontent.com/29832137/78464587-87f57e80-76c1-11ea-9962-11b9bc9e0b0e.png)

**Comment by Rammelkast** [comment]
Hi,
Thank you for reporting this. Can you send me your: Server software type (Bukkit/Spigot/Other) and it's version. Also, do you happen to know under what conditions these false positives occur?

**Comment by XmatrixX97** [comment]
i am using it with bukkit 1.15.2
and goes through anything, swimming, running, jumping

**Comment by Rammelkast** [comment]
Can you show me the results of the following commands:
/gc
/tps

And have you modified you magic.yml?

**Comment by XmatrixX97** [comment]
> And have you modified you magic.yml?
Yes, and starts to give errors in the console
[2020-04-05-2.log](https://github.com/Rammelkast/AntiCheatReloaded/files/4434480/2020-04-05-2.log)

here is the modified magic file _(change the extension to .log because github wouldn't let me upload it)_
[magic.log](https://github.com/Rammelkast/AntiCheatReloaded/files/4434495/magic.log)

**these commands you tell me don't work**

**Comment by Rammelkast** [comment]
Regarding the console errors, please check Y_MAXVIOLATIONS in your magic.yml. This must be an integer (a number with no decimals).
For your WaterWalk false positives, the settings WATER_SPEED_VIOLATION_MAX to 16 and increase this further if you continue to have false positives.
I do not know where the speed false positives come from. Do you run any plugins that change the players moving speed?

**Comment by Rammelkast** [comment]
Closed due to lack of response.
