### ISSUE TITLE
New to ACR..

### ISSUE THREAD

**Issue by GalaxyWolfxD** [Rammelkast/AntiCheatReloaded#61]
I have just installed this plugin to my server and it does work perfectly fine but the option for ban doesn't work? Is there something I need to enable or disable? 
- I'm also pretty new to anti cheats as I normally just use whitelisting aha..

Also, forgot to add this.. is there any way to not have spammed messages from it? Can hardly see my screen lol

**Comment by EncryptSL** [comment]
If i understand you mean Notification messages. And you can't see chat.

**Comment by Rammelkast** [comment]
As an operator there is currently no way to opt-out of these messages because of the permission usage. I'll fix this in the next build. As for the ban option, can you send me your config.yml and groups.yml

**Comment by GalaxyWolfxD** [comment]
[groups.txt](https://github.com/Rammelkast/AntiCheatReloaded/files/4441980/groups.txt)
[config.txt](https://github.com/Rammelkast/AntiCheatReloaded/files/4441981/config.txt)

- is there also any way to stop from random kicking? I apologize for so many questions

**Comment by Rammelkast** [comment]
In your groups.yml you can configure default actions. To disable the kicking, change KICK to NONE for the 'high' group. To autoban create a new group and set it up. You can use the custom template (line 5 of groups.yml). I suggest you use a high VL value (custom has -1, change this) like 250 to prevent false bans,

**Comment by GalaxyWolfxD** [comment]
Ah okay! thank you
