### ISSUE TITLE
scaffold, horses, trapdoors and water

### ISSUE THREAD

**Issue by zancholy** [Rammelkast/AntiCheatReloaded#63]
scaffold just full stop is broken it is detected by 3 things speed, spider and fly spider being the most punishing.

horses get detected for fly and you get kicked off the horse when you do a full jump while moving.

trapdoors count as a non climbable surface and get detected by illegal movement and fly

water is broken if you hold space detects as Jesus.

**Comment by Rammelkast** [comment]
Can you explain the trapdoors a little further?

**Comment by Rammelkast** [comment]
Closing: lack of response

**Comment by bertugarangou** [comment]
As zancholy couldn't repply I will: when climbing ladders and going trough trapdors, it detects spider (picture).
![image](https://user-images.githubusercontent.com/42043974/79051360-16bd4a80-7c30-11ea-8433-cee00a0f488d.png)

**Comment by Rammelkast** [comment]
Thank you for explaining, I'll have a look at it.
