### ISSUE TITLE
False Positive with Blink

### ISSUE THREAD

**Issue by NickPlayzMC** [Rammelkast/AntiCheatReloaded#64]
[INFO|7:23:30]: ACR _NickPlayzMC failed Blink | sent 26 packets in one second (max=25, leniency=1.0, ping=104) | ping: 104ms 

This messaged popped up when I was on my server. I don't have any Cheats installed. Looks like a false positive.

**Comment by Rammelkast** [comment]
Open magic.yml and change BLINK_PACKET to 30 and BLINK_AVERAGE_PING to 200. If this still gives false-positives keep increasing BLINK_PACKET until they disappear.
