### ISSUE TITLE
question for the plugin 

### ISSUE THREAD

**Issue by DiamondLordGR** [Rammelkast/AntiCheatReloaded#67]
Hello, I installed AntiCheatReloaded on my server and i get to many false positives about FastHeal. What value should I change to get rid of all the false positives and in what number should I change it?(if you know)
Thank you for your help and for the creation of AntiCheat

**Comment by Rammelkast** [comment]
Can you give me more information on when the false positive occurs?

**Comment by DiamondLordGR** [comment]
It happens when players eat and then regenerate life
Also we get a lot of blink reports. We used the command /acr check BLINK off but it still gives as reports on BLINK :
https://prnt.sc/rwqeqq
https://prnt.sc/rwk65l
https://prnt.sc/rwqev9
