### ISSUE TITLE
False positive killaura

### ISSUE THREAD

**Issue by bertugarangou** [Rammelkast/AntiCheatReloaded#68]
Detects kill aura for incorrect angle (~330) when it is in front of the player

![image](https://user-images.githubusercontent.com/42043974/79015696-99c99c80-7b6d-11ea-877f-787cdabe3dd6.png)

More examples:
https://hastebin.com/ixelegupal.md

Paper spigot 1.15.2 -- # 164.
Plugin version 1.8.0

**Comment by Rammelkast** [comment]
Could not replicate.

**Comment by bertugarangou** [comment]
So what you recomend me to solve this? I already tried reonstall the plugin

**Comment by Rammelkast** [comment]
Does this still happen a lot? If so, please tell me the exact conditions under which this happens.

**Comment by bertugarangou** [comment]
Yes very often, it doesn't seem to be a pattern. It happens when someone fights an animal or a mob facing it, and ACR says incorrect angle around 300 when it's near 0 (in front of the player).

**Comment by Rammelkast** [comment]
Reopened issue: Possible issue with clamping(?) angle.

**Comment by Rammelkast** [comment]
Can you try to submit a video?

**Comment by bertugarangou** [comment]
Yes I extremed the situation attacking more mobs to get more alerts, the normal case it shows is when killing mobs/animals in any angle (as the picture in the first post, on a farm for example).  I hope it is useful.

[https://imgur.com/a/6DtleJ7](https://imgur.com/a/6DtleJ7)

**Comment by Rammelkast** [comment]
Thank you, this helps a lot. I'm currently trying to debug why this is happening and I'll try to fix it asap.

**Comment by Rammelkast** [comment]
I can't seem to replicate this. Can you send me a list of all your plugins?

**Comment by bertugarangou** [comment]
It also happens when I disable all plugins

**Comment by lowlevelm** [comment]
I am having the same issue

**Comment by Rammelkast** [comment]
> I am having the same issue

Do you happen to run Paper as well?

**Comment by lowlevelm** [comment]
> Do you happen to run Paper as well?
Yes

**Comment by Rammelkast** [comment]
I still can't seem to replicate this. Is there a specific way to get this to false positive?

**Comment by Rammelkast** [comment]
Could not replicate, no longer an active thread.
