### ISSUE TITLE
Player Teleporting back were they died when they get killed instead of spawn.

### ISSUE THREAD

**Issue by Villalon17** [Rammelkast/AntiCheatReloaded#74]
Hey! I'm Villalon and I'm trying to help a server with your plugin "Anti Cheat Reloaded". Its a kit PVP server with a version plugin up to 1.7-1.15.2. The problem is that a player can die during the map and then wont be teleported back to spawn. They will be teleported back to where they died because the anti-cheat stops them from that. Any help would be grateful and I'm looking forward to talking further in the future. Thanks -Villalon

**Comment by Rammelkast** [comment]
This issue has been fixed in commit 9771387 and will be in the next release.
