### ISSUE TITLE
Blink False Readings

### ISSUE THREAD

**Issue by FlamingBirdz** [Rammelkast/AntiCheatReloaded#75]
For some reason players, including me, are said to be using blink when they are not.  Before ACR says they are, players are just walking/sprinting around.  I have no idea why this is happening.

**Comment by Rammelkast** [comment]
This is probably a combination of the very strict default ruleset and lag. Open magic.yml and change BLINK_PACKET to 30 or higher, depending on where the false positives stop showing.
