### ISSUE TITLE
Make getHandlerList() static

### ISSUE THREAD

**Issue by BlazingAsher** [Rammelkast/AntiCheatReloaded#76]
Hello,
I am currently trying to write a custom handler for the CheckFailEvent. However, you seem to have forgotten to make the getHandlerList() method static.

Many thanks

**Comment by Rammelkast** [comment]
I merged to check for validity, but it looks like getHandlers() shouldn't even be static.

**Comment by BlazingAsher** [comment]
That's odd, I have always done it this way and the SpigotAPI docs seem to suggest otherwise:
https://www.spigotmc.org/wiki/using-the-event-api/ (Section 3).

**Comment by Rammelkast** [comment]
I added it according to the Spigot API docs.
