### ISSUE TITLE
false positive: walking up beds

### ISSUE THREAD

**Issue by t3hdon** [Rammelkast/AntiCheatReloaded#79]
ACR triggered a failed speed alert when walking onto a bed without jumping.

alert:
failed Speed | y speed was too high (speed=0.5625, max=0.5175) | ping: 0ms, tps: 20

to replicate, place a bed down and attempt to walk forward toward one of the bed sides.

**Comment by Rammelkast** [comment]
Fixed in latest commit. Please wait for a release or build the plugin from it's source.
