### ISSUE TITLE
Elytra Is Like Survivel Flight.

### ISSUE THREAD

**Issue by bluefutureMC** [Rammelkast/AntiCheatReloaded#8]
if a player is using an elytra then he is getting kicked for flying.

feature request:
disable and enable types of checks

**Comment by Rammelkast** [comment]
This should not happen, for what check is the player getting kicked, flight, YAxis, or an other check?

**Comment by bluefutureMC** [comment]
YAxis, maybe it is because i use an elytra booster plugin?

**Comment by Rammelkast** [comment]
That probably plays a big part in the problem yes, but still, it SHOULD give no problems.

Anyway, thanks for reporting, i'll start working on it tomorrow.

**Comment by bluefutureMC** [comment]
thank you for the fast support! :)

**Comment by Rammelkast** [comment]
The false positive is now fixed and is included in the next update.

**Comment by bluefutureMC** [comment]
thx

**Comment by bluefutureMC** [comment]
Sorry if I'm bothering you but when do the new update is coming?

i really like your plugin and i think it is really good also.
