### ISSUE TITLE
Severe False Positives.

### ISSUE THREAD

**Issue by DamianJBurgos** [Rammelkast/AntiCheatReloaded#82]
Hello, 

My players are constantly getting False Positives when doing basic things such as simply walking.

Please see attached screenshots.

<img width="1440" alt="Screen Shot 2020-05-04 at 3 36 58 PM" src="https://user-images.githubusercontent.com/16234394/81006319-52a59300-8e1d-11ea-8af3-aecce2809e79.png">
<img width="1440" alt="Screen Shot 2020-05-04 at 3 37 11 PM" src="https://user-images.githubusercontent.com/16234394/81006320-533e2980-8e1d-11ea-8fbf-e6738ef9c02e.png">

**Comment by Rammelkast** [comment]
Can you send me the following;
- Spigot version
- Server TPS (found by either /gc or /tps)

When these two false positives _exactly_ occur.
Thank you.

**Comment by DamianBurgos** [comment]
Spigot Verison: Latest Stable Build as of 5/4/2020
TPS: Has never dropped below 19.

<img width="1440" alt="Screen Shot 2020-05-04 at 4 28 46 PM" src="https://user-images.githubusercontent.com/16234394/81010515-6d2f3a80-8e24-11ea-85f9-ea4a5c356c49.png">

**Comment by DamianBurgos** [comment]
If you would like to join the server yourself and see how easily false positives happen, let me know and I can give you the server address and or OP so you can see the console.

**Comment by Rammelkast** [comment]
Do these FastPlace false positives still occur? If so, in what gamemode and under what conditions?

**Comment by DamianBurgos** [comment]
I had to remove the plugin due to the fact it kept doing it.

In survival and as I said before simply walking will cause it to happen.

**Comment by Rammelkast** [comment]
So the **FastPlace** false positive occurred when walking? Or was this FastHeal?

**Comment by DamianBurgos** [comment]
While simply walking.....

**Comment by Rammelkast** [comment]
Can you tell me the following:
Do you run ViaVersion, ViaBackwards or ProtocolSupport?
Do people use autoclickers?

**Comment by Rammelkast** [comment]
Could not replicate.
