### ISSUE TITLE
getting a lot of false positives when jumping

### ISSUE THREAD

**Issue by Ron0x99** [Rammelkast/AntiCheatReloaded#84]
Hi there, we get a lot of false positives when I just jump a few times (we all get this on the server). It say's:
"ACR Ron0x failed Flight | type=gravity, offset=0.15) | ping: 41ms, tps: 20"

It does that every time someone just jumps. I disabled it now in the config as ignored. But maybe you want to fix this later on?

**Comment by rsammelson** [comment]
I also had this issue

**Comment by Rammelkast** [comment]
I assume with jumping a few times you mean sprintjumping ahead?

**Comment by rsammelson** [comment]
Yes, that is correct.
