### ISSUE TITLE
100% & 120% speed bypass

### ISSUE THREAD

**Issue by kawaii-neverhide** [Rammelkast/AntiCheatReloaded#85]
https://www.youtube.com/watch?v=eDAmqF3Hxpw

**Comment by Rammelkast** [comment]
Can you give me some more information on how this works?

**Comment by kawaii-neverhide** [comment]
> Can you give me some more information on how this works?

Video contains settings. It works like bad timer check && bad max speed && fast jump speed. Cubecraft fly just bad max speed check

**Comment by Rammelkast** [comment]
Seen as duplicate of #73
