### ISSUE TITLE
ElytraFly False Flag

### ISSUE THREAD

**Issue by Oecher1** [Rammelkast/AntiCheatReloaded#87]
on 1.15.2 go into a ocean have a elytra on with fireworks glide with elytra into water then just use fireworks to move forward faster and you will also false flag speed sometimes and sometimes moving up with out the new swimming animation will also false elytrafly

**Comment by rur0** [comment]
I also can reproduce described by @Oecher1 
In addition, you are frozen in place when in water, even underwater so you will drown if you don't take off the elytra.
