### ISSUE TITLE
READ THIS IF YOU RUN ON MC 1.16+

### ISSUE THREAD

**Issue by Rammelkast** [Rammelkast/AntiCheatReloaded#89]
AntiCheatReloaded does **NOT** support Minecraft 1.16+ as of now!
All issues on 1.16+ or compatibility issues will therefore be marked als "Wont fix" and closed!

**Comment by ClientKitty** [comment]
But will you update it to 1.16 at some point.

**Comment by Rammelkast** [comment]
@ClientKitty Yes.

**Comment by koalabear166** [comment]
When will u update it?
