### ISSUE TITLE
Players using the Elytra

### ISSUE THREAD

**Issue by VulcanNetworks** [Rammelkast/AntiCheatReloaded#9]
Unranked and unopped players who are using the Elytra are being detected as using speed hacks.

Could this be looked into?
![2016-08-18_04 27 01](https://cloud.githubusercontent.com/assets/12189409/17761071/0ac5583e-64fc-11e6-83df-13072b6bb8df.png)

**Comment by Augustin37** [comment]
Could you fix this bug? Just because of this, I can't use the plugin /:
