### ISSUE TITLE
Disabler + Infinite fly bypass

### ISSUE THREAD

**Issue by Strikeless** [Rammelkast/AntiCheatReloaded#92]
Version: 1.8.2 (latest atm)

You can disable every check except MorePackets by toggling sprint around every 4 ticks.

Currently the only fly check that seems to be catching flies are glide and the 5.5 block check, glide only gets triggered once you go down, but if you don't go down, the only check to prevent you fron flying is the 5.5 check, which can be bypassed by porting over it at around 4.5 blocks in and sending C04 to the latest grounded position. (if that wasn't the case please reply that it didn't work and i'll open up the bypass to see how it worked, just took that out from my memory)

**Comment by Rammelkast** [comment]
Considering this fixed as of 2086a01
