### ISSUE TITLE
Tons of false positives

### ISSUE THREAD

**Issue by darkmage4** [Rammelkast/AntiCheatReloaded#98]
There seems to be tons of false positives in 1.9.1 Where if someone TP's, and sometimes the chunks don't load properly, you fall through the ground, and it thinks you're cheating. I have Spigot 1.16.1. Skyblock, you fall into the void, and it thinks you're cheating and kicks you. Getting tons of bad packets as well on bad connection.

**Comment by Rammelkast** [comment]
What check falses when you fall into the void?

**Comment by darkmage4** [comment]
When you're falling into the void, it says BadPackets and then kicks the player for hacks.

**Comment by Rammelkast** [comment]
I fixed that in the latest update, any other issues?

**Comment by Rammelkast** [comment]
Closing due to lack of response.

**Comment by darkmage4** [comment]
Yeah, it seems to kick players when they're not even hacking, someone loaded in, and then got kicked for no reason. I loaded up my alt with no mods except for mini map, and it just says kicked for cheating when barely walking. this is the recent version. It was false positive on everything, when standing still it kicked for flying. Another user got kicked for just logging in.
