### ISSUE TITLE
Player unable to move on slab and gets kicked

### ISSUE THREAD

**Issue by itsgaryk** [Rammelkast/AntiCheatReloaded#99]
A player got stuck on a wooden slab. When they tried moving they were stuttering on the spot and after 1-2 seconds of movement the plugin kicked them.

After giving them the permission anticheat.check.exempt they were able to move freely again and not get kicked.

Running PaperMC build 130

Plugins used
BackupOnEvent*, ConsoleSpamFix, DeadChest, DiscordSRV, DropHeads, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, InstantBreak*, LuckPerms, Pingas*, PlugMan, ProtocolLib, SilkSpawners, SmoothSleep, uShop, Vault, WorldEdit

**Comment by Rammelkast** [comment]
Duplicate #96, already fixed in c74fc92
